"""Initial migration

Revision ID: 4087c43f0c7c
Revises:
Create Date: 2026-02-21 04:53:47.141140

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import edupsyadmin.db.clients

# revision identifiers, used by Alembic.
revision: str = "4087c43f0c7c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column(
            "first_name_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "last_name_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "gender_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "birthday_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "street_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "city_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "parent_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "telephone1_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "telephone2_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "email_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column(
            "notes_encr", edupsyadmin.db.clients.EncryptedString(), nullable=False
        ),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("school", sa.String(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("class_name", sa.String(), nullable=True),
        sa.Column("class_int", sa.Integer(), nullable=True),
        sa.Column("estimated_graduation_date", sa.Date(), nullable=True),
        sa.Column("document_shredding_date", sa.Date(), nullable=True),
        sa.Column(
            "keyword_taet_encr",
            edupsyadmin.db.clients.EncryptedString(),
            nullable=False,
        ),
        sa.Column(
            "lrst_diagnosis_encr",
            edupsyadmin.db.clients.EncryptedString(),
            nullable=False,
        ),
        sa.Column(
            "lrst_last_test_date_encr",
            edupsyadmin.db.clients.EncryptedString(),
            nullable=False,
        ),
        sa.Column(
            "lrst_last_test_by_encr",
            edupsyadmin.db.clients.EncryptedString(),
            nullable=False,
        ),
        sa.Column("datetime_created", sa.DateTime(), nullable=False),
        sa.Column("datetime_lastmodified", sa.DateTime(), nullable=False),
        sa.Column("notenschutz", sa.Boolean(), nullable=False),
        sa.Column("nos_rs", sa.Boolean(), nullable=False),
        sa.Column("nos_rs_ausn", sa.Boolean(), nullable=False),
        sa.Column("nos_rs_ausn_faecher", sa.String(), nullable=True),
        sa.Column("nos_les", sa.Boolean(), nullable=False),
        sa.Column("nos_other", sa.Boolean(), nullable=False),
        sa.Column("nos_other_details", sa.String(), nullable=True),
        sa.Column("nachteilsausgleich", sa.Boolean(), nullable=False),
        sa.Column("nta_zeitv", sa.Boolean(), nullable=False),
        sa.Column("nta_zeitv_vieltext", sa.Integer(), nullable=True),
        sa.Column("nta_zeitv_wenigtext", sa.Integer(), nullable=True),
        sa.Column("nta_font", sa.Boolean(), nullable=False),
        sa.Column("nta_aufg", sa.Boolean(), nullable=False),
        sa.Column("nta_struktur", sa.Boolean(), nullable=False),
        sa.Column("nta_arbeitsm", sa.Boolean(), nullable=False),
        sa.Column("nta_ersgew", sa.Boolean(), nullable=False),
        sa.Column("nta_vorlesen", sa.Boolean(), nullable=False),
        sa.Column("nta_other", sa.Boolean(), nullable=False),
        sa.Column("nta_other_details", sa.String(), nullable=True),
        sa.Column("nta_nos_notes", sa.String(), nullable=True),
        sa.Column("nta_nos_end", sa.Boolean(), nullable=False),
        sa.Column("nta_nos_end_grade", sa.Integer(), nullable=True),
        sa.Column("min_sessions", sa.Integer(), nullable=False),
        sa.Column("n_sessions", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
